# Copyright 2026 Durga Prasad Raju Nadimpalli
# Licensed under the Apache License, Version 2.0

global:
  environment: dev
  imagePullPolicy: IfNotPresent

apiGateway:
  replicaCount: 1
  image: cloudpulse/api-gateway:0.1.0
  port: 8080

collector:
  replicaCount: 2
  image: cloudpulse/collector:0.1.0
  port: 8081

analyzer:
  replicaCount: 1
  image: cloudpulse/analyzer:0.1.0
  port: 8082

correlator:
  replicaCount: 1
  image: cloudpulse/correlator:0.1.0
  port: 8083

notifier:
  replicaCount: 1
  image: cloudpulse/notifier:0.1.0
  port: 8084

postgres:
  enabled: true

redis:
  enabled: true
